// https://leetcode.com/problems/find-the-difference/description/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {

    // convert string s to array using spread operator [...]
    let arr = [...s];

    // loop through every character of string t
    for (let i = 0; i < t.length; i++) {

        // if every character string t is includes in string s
        if (arr.includes(t[i])) {

            // find index of t[i] in arr
            let index = arr.indexOf(t[i]);

            // remove the index element from array arr using splice() 
            arr.splice(index, 1);

        } else { // else return that character of string t
            return t[i];
        }
    }
};

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/


/*
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
*/


/*
Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/